name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Adjust to your .NET version

      # Step 3: Restore dependencies for the solution
      - name: Restore dependencies
        run: dotnet restore Lab-7/Lab5

      # Step 4: Build the solution
      - name: Build the solution
        run: dotnet build Lab-7/Lab5 --no-restore

      # Step 5: Run tests for the solution
      - name: Run tests
        run: dotnet test Lab-7/TestLab6 --no-build --verbosity normal
