name: .NET Core Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Specify your .NET version here

    - name: Restore dependencies
      run: |
        cd Lab5  # Navigate to the folder containing your .csproj
        dotnet restore

    - name: Build
      run: |
        cd Lab5
        dotnet build --configuration Release

    - name: Run tests
      run: |
        cd TestLab6
        dotnet test
